name: lualepapp
description: Lúa Lếp App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1+19

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: any
  flutter_native_splash: any
  flutter_overboard: ^1.1.5
  shared_preferences: ^0.5.7+3
  firebase_database: ^3.1.6
  firebase_auth: ^0.16.1
  firebase_analytics: ^5.0.15
  firebase_core: ^0.4.5
  firebase_admob: ^0.9.3+4
  rxdart: ^0.24.1
  firebase_storage: ^3.1.6
  cached_network_image: ^2.2.0+1
  random_color: ^1.0.5
  flutter_audio_recorder: ^0.5.5
  path_provider: ^1.6.11
  file: ^5.2.0
  audioplayers: ^0.15.1
  liquid_pull_to_refresh: ^2.0.0
  flutter_sentry: ^0.4.2
  sentry: any
  dio: ^3.0.9
  confetti: ^0.5.2
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.7

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/LUA_LEP_ICON.png"
  image_path_android: "assets/launcher/LUA_LEP_ICON.png"
  adaptive_icon_background: "assets/launcher/LUA_LEP_BACKGROUND.png"
  adaptive_icon_foreground: "assets/launcher/LUA_LEP_FOREGROUND.png"

flutter_native_splash:
  image: assets/launcher/LUA_LEP_SPLASH.png
  color: "000000"
  fill: true
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/launcher/LUA_LEP_FOREGROUND.png
    - assets/launcher/LUA_LEP_BACKGROUND.png
    - assets/launcher/LUA_LEP_ICON.png
    - assets/illustrations/abstract-1.png
    - assets/illustrations/abstract-2.png
    - assets/illustrations/abstract-3.png
    - assets/illustrations/abstract-4.png
    - assets/illustrations/abstract-5.png
    - assets/illustrations/abstract-6.png
    - assets/illustrations/abstract-7.png
    - assets/illustrations/abstract-8.png
    - assets/illustrations/abstract-9.png
    - assets/illustrations/abstract-10.png
    - assets/illustrations/flame-2.png
    - assets/illustrations/flame-no-comments.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
